<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="correspondencemodel" nsURI="http://www.example.org/correspondencemodel"
    nsPrefix="correspondencemodel">
  <eClassifiers xsi:type="ecore:EClass" name="Component2Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcmComponent" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//repository/BasicComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="javaClass" lowerBound="1"
        eType="ecore:EClass ../../edu.kit.kastel.scbs.pcm2java4joana.sourcecode/model/sourcecode.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface2interface" upperBound="-1"
        eType="#//Interface2Interface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface2Interface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcmInterface" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="javaInterface" lowerBound="1"
        eType="ecore:EClass ../../edu.kit.kastel.scbs.pcm2java4joana.sourcecode/model/sourcecode.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation2method" upperBound="-1"
        eType="#//Operation2Method" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation2Method">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcmOperation" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationSignature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="javaMethod" lowerBound="1"
        eType="ecore:EClass ../../edu.kit.kastel.scbs.pcm2java4joana.sourcecode/model/sourcecode.ecore#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter2parameter" upperBound="-1"
        eType="#//Parameter2Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter2Parameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcmParameter" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//repository/Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="javaParameter" lowerBound="1"
        eType="ecore:EClass ../../edu.kit.kastel.scbs.pcm2java4joana.sourcecode/model/sourcecode.ecore#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralCorrespondenceModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component2class" upperBound="-1"
        eType="#//Component2Class" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
