/**
 */
package edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.provider;

import edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.util.CorrespondencemodelAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class CorrespondencemodelItemProviderAdapterFactory extends CorrespondencemodelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public CorrespondencemodelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.Component2Class} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Component2ClassItemProvider component2ClassItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.Component2Class}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponent2ClassAdapter() {
		if (component2ClassItemProvider == null) {
			component2ClassItemProvider = new Component2ClassItemProvider(this);
		}

		return component2ClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.Interface2Interface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Interface2InterfaceItemProvider interface2InterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.Interface2Interface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterface2InterfaceAdapter() {
		if (interface2InterfaceItemProvider == null) {
			interface2InterfaceItemProvider = new Interface2InterfaceItemProvider(this);
		}

		return interface2InterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.Operation2Method} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Operation2MethodItemProvider operation2MethodItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.Operation2Method}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperation2MethodAdapter() {
		if (operation2MethodItemProvider == null) {
			operation2MethodItemProvider = new Operation2MethodItemProvider(this);
		}

		return operation2MethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.Parameter2Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Parameter2ParameterItemProvider parameter2ParameterItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.Parameter2Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameter2ParameterAdapter() {
		if (parameter2ParameterItemProvider == null) {
			parameter2ParameterItemProvider = new Parameter2ParameterItemProvider(this);
		}

		return parameter2ParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.StructuralCorrespondenceModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StructuralCorrespondenceModelItemProvider structuralCorrespondenceModelItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.StructuralCorrespondenceModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStructuralCorrespondenceModelAdapter() {
		if (structuralCorrespondenceModelItemProvider == null) {
			structuralCorrespondenceModelItemProvider = new StructuralCorrespondenceModelItemProvider(this);
		}

		return structuralCorrespondenceModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.PCMElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PCMElementItemProvider pcmElementItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.PCMElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPCMElementAdapter() {
		if (pcmElementItemProvider == null) {
			pcmElementItemProvider = new PCMElementItemProvider(this);
		}

		return pcmElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.PCMComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PCMComponentItemProvider pcmComponentItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.PCMComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPCMComponentAdapter() {
		if (pcmComponentItemProvider == null) {
			pcmComponentItemProvider = new PCMComponentItemProvider(this);
		}

		return pcmComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.PCMInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PCMInterfaceItemProvider pcmInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.PCMInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPCMInterfaceAdapter() {
		if (pcmInterfaceItemProvider == null) {
			pcmInterfaceItemProvider = new PCMInterfaceItemProvider(this);
		}

		return pcmInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.PCMOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PCMOperationItemProvider pcmOperationItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.PCMOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPCMOperationAdapter() {
		if (pcmOperationItemProvider == null) {
			pcmOperationItemProvider = new PCMOperationItemProvider(this);
		}

		return pcmOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.PCMParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PCMParameterItemProvider pcmParameterItemProvider;

	/**
	 * This creates an adapter for a {@link edu.kit.kastel.scbs.pcm2java4joana.correspondencemodel.PCMParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPCMParameterAdapter() {
		if (pcmParameterItemProvider == null) {
			pcmParameterItemProvider = new PCMParameterItemProvider(this);
		}

		return pcmParameterItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (component2ClassItemProvider != null) component2ClassItemProvider.dispose();
		if (interface2InterfaceItemProvider != null) interface2InterfaceItemProvider.dispose();
		if (operation2MethodItemProvider != null) operation2MethodItemProvider.dispose();
		if (parameter2ParameterItemProvider != null) parameter2ParameterItemProvider.dispose();
		if (structuralCorrespondenceModelItemProvider != null) structuralCorrespondenceModelItemProvider.dispose();
		if (pcmElementItemProvider != null) pcmElementItemProvider.dispose();
		if (pcmComponentItemProvider != null) pcmComponentItemProvider.dispose();
		if (pcmInterfaceItemProvider != null) pcmInterfaceItemProvider.dispose();
		if (pcmOperationItemProvider != null) pcmOperationItemProvider.dispose();
		if (pcmParameterItemProvider != null) pcmParameterItemProvider.dispose();
	}

}
