/**
 *
 * $Id$
 */
package edu.kit.kastel.scbs.pcm2java4joana.securitycorrespondencemodel.validation;

import edu.kit.kastel.scbs.pcm2java4joana.joana.Annotation;

import edu.kit.kastel.scbs.pcm2java4joana.securitycorrespondencemodel.Conf4CBSEParametersAndDataPair;

/**
 * A sample validator interface for {@link edu.kit.kastel.scbs.pcm2java4joana.securitycorrespondencemodel.ParametersAndDataPair2Annotation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParametersAndDataPair2AnnotationValidator {
	boolean validate();

	boolean validateJoanaAnnotation(Annotation value);
	boolean validateConf4cbseparametersanddatapair(Conf4CBSEParametersAndDataPair value);
}
