<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="correspondences" nsURI="http://www.example.org/correspondences"
    nsPrefix="correspondences">
  <eClassifiers xsi:type="ecore:EClass" name="CorrespondenceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PCMComponent" eSuperTypes="#//CorrespondenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcmprovidedinterfaces"
        upperBound="-1" eType="#//PCMProvidedInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceCodeClass" eSuperTypes="#//CorrespondenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcecodemethod" upperBound="-1"
        eType="#//SourceCodeMethod" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceCodeMethod" eSuperTypes="#//CorrespondenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcecodeparamter" upperBound="-1"
        eType="#//SourceCodeParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PCMProvidedInterface" eSuperTypes="#//CorrespondenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcmmethod" upperBound="-1"
        eType="#//PCMMethod" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PCMMethod" eSuperTypes="#//CorrespondenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcmparameter" upperBound="-1"
        eType="#//PCMParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceCodeParameter" eSuperTypes="#//CorrespondenceElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PCMParameter" eSuperTypes="#//CorrespondenceElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentCorrespondence" eSuperTypes="#//CorrespondenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcmcomponent" lowerBound="1"
        eType="#//PCMComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcecodeclass" lowerBound="1"
        eType="#//SourceCodeClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodcorrespondence" upperBound="-1"
        eType="#//MethodCorrespondence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodCorrespondence" eSuperTypes="#//CorrespondenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcmmethod" eType="#//PCMMethod"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcecodemethod" eType="#//SourceCodeMethod"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametercorrespondence"
        upperBound="-1" eType="#//ParameterCorrespondence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterCorrespondence" eSuperTypes="#//CorrespondenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcecodeparamter" eType="#//SourceCodeParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcmparameter" eType="#//PCMParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CorrespondenceModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentcorrespondence"
        upperBound="-1" eType="#//ComponentCorrespondence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfacecorrespondence"
        upperBound="-1" eType="#//InterfaceCorrespondence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceCorrespondence" eSuperTypes="#//CorrespondenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcecodeinterface" lowerBound="1"
        eType="#//SourceCodeInterface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcmprovidedinterface" eType="#//PCMProvidedInterface"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodcorrespondence" upperBound="-1"
        eType="#//MethodCorrespondence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceCodeInterface" eSuperTypes="#//CorrespondenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcecodemethod" upperBound="-1"
        eType="#//SourceCodeMethod" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
