/**
 *
 * $Id$
 */
package edu.kit.kastel.scbs.pcm2java4joana.joana.validation;

import edu.kit.kastel.scbs.pcm2java4joana.sourcecode.Method;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link edu.kit.kastel.scbs.pcm2java4joana.joana.FlowSpecificationElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FlowSpecificationElementValidator {
	boolean validate();

	boolean validateTag(EList<String> value);

	boolean validateTag(String value);
	boolean validateAnnotatedClass(edu.kit.kastel.scbs.pcm2java4joana.sourcecode.Class value);
	boolean validateAnnotatedMethod(Method value);
}
