/**
 *
 * $Id$
 */
package edu.kit.kastel.scbs.pcm2java4joana.joanasimplifiedresult.validation;


/**
 * A sample validator interface for {@link edu.kit.kastel.scbs.pcm2java4joana.joanasimplifiedresult.ResultType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResultTypeValidator {
	boolean validate();

	boolean validateTypeString(String value);
}
