/**
 *
 * $Id$
 */
package edu.kit.kastel.scbs.pcm2java4joana.joanasimplifiedresult.validation;

import edu.kit.kastel.scbs.pcm2java4joana.joanasimplifiedresult.ResultMethod;

/**
 * A sample validator interface for {@link edu.kit.kastel.scbs.pcm2java4joana.joanasimplifiedresult.TraceState}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TraceStateValidator {
	boolean validate();

	boolean validateTracePosition(int value);
	boolean validateTraceClassName(String value);
	boolean validateSecurityLevelName(String value);
	boolean validateParameterIndex(int value);
	boolean validateResultmethod(ResultMethod value);
}
